version: '3'

services:
  app:
    build: ./
    volumes:
      - ./src:/usr/app
    command: sh -c "yarn dev"
    ports:
      - "3000:3000"
    networks:
      - json-server-todo_app-network
      # - app-network

networks:
  json-server-todo_app-network:
    external: true
    # driver: bridge
  # app-network:
    # driver: bridge
